# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{session_captcha}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Kjel Delaey}]
  s.date = %q{2011-09-06}
  s.description = %q{SessionCaptcha is an easy to use CAPTCHA plugin that uses the session to temporarily store the hashed value of the generated secret. The secret and image are securely destroyed after completion of the transaction.}
  s.email = %q{}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "lib/generators/session_captcha_generator.rb",
    "lib/generators/templates/partial.erb",
    "lib/generators/templates/session_captcha.rb",
    "lib/session_captcha.rb",
    "lib/session_captcha/controller.rb",
    "lib/session_captcha/form_builder.rb",
    "lib/session_captcha/formtastic.rb",
    "lib/session_captcha/image.rb",
    "lib/session_captcha/railtie.rb",
    "lib/session_captcha/utils.rb",
    "lib/session_captcha/view.rb"
  ]
  s.homepage = %q{}
  s.require_paths = [%q{lib}]
  s.rubyforge_project = %q{}
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{SessionCaptcha is an easy to use CAPTCHA plugin that uses the session to temporarily store the hashed value of the generated secret.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

